// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybulwqfqefxraxpjtbtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidWx3cWZxZWZ4cmF4cGp0YnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODgwMzIsImV4cCI6MjA2MTE2NDAzMn0.X-lU5yTZ-sht1swmDYZC0YI7xWzAhbwi5-q_YxSY2PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);